"""Where each editable player value lives, in every version that stores it.

GENERATED by tools/extract_mc_schema.py -- do not edit by hand. Regenerate with

    python tools/extract_mc_schema.py --workspace "<decompiled workspace>"

Source of truth: Minecraft 26.2, 2026-08-25.

Two halves, and the difference matters when you are deciding whether to trust
an entry. Tag names, types and version boundaries are *extracted* -- read off
the game's own ValueInput/ValueOutput accessors and its data-fix registry, so
they are as right as the sources are. Bounds, editability and the reset lists
are *curated* -- they encode what this editor chooses to allow, and no amount
of reading Mojang's code will confirm them.

This module is pure data with no internal imports, so it sits in the bottom
layer alongside nbt and util.
"""

from dataclasses import dataclass, field
from typing import Optional


# NBT tag constants, mirrored from mcsm.nbt so this module stays importable on
# its own. Kept in sync by test_playerdat_schema.
TAG_END = 0
TAG_BYTE = 1
TAG_SHORT = 2
TAG_INT = 3
TAG_LONG = 4
TAG_FLOAT = 5
TAG_DOUBLE = 6
TAG_BYTE_ARRAY = 7
TAG_STRING = 8
TAG_LIST = 9
TAG_COMPOUND = 10
TAG_INT_ARRAY = 11
TAG_LONG_ARRAY = 12

TAG_NAMES = {
    TAG_BYTE: "TAG_Byte", TAG_SHORT: "TAG_Short", TAG_INT: "TAG_Int",
    TAG_LONG: "TAG_Long", TAG_FLOAT: "TAG_Float", TAG_DOUBLE: "TAG_Double",
    TAG_BYTE_ARRAY: "TAG_Byte_Array", TAG_STRING: "TAG_String",
    TAG_LIST: "TAG_List", TAG_COMPOUND: "TAG_Compound",
    TAG_INT_ARRAY: "TAG_Int_Array", TAG_LONG_ARRAY: "TAG_Long_Array",
}



@dataclass(frozen=True)
class Variant:
    """One historical shape of a field.

    `min_dv`/`max_dv` are inclusive DataVersion bounds; None at either end
    means unbounded. A file with no DataVersion tag at all predates 1.9 and is
    matched against the oldest variant."""

    path: tuple
    tag: int
    item: Optional[int] = None
    count: Optional[int] = None
    min_dv: Optional[int] = None
    max_dv: Optional[int] = None

    def covers(self, data_version: Optional[int]) -> bool:
        dv = 0 if data_version is None else data_version
        if self.min_dv is not None and dv < self.min_dv:
            return False
        if self.max_dv is not None and dv > self.max_dv:
            return False
        return True

    def describe(self) -> str:
        name = TAG_NAMES.get(self.tag, str(self.tag))
        if self.item is not None:
            name += f"<{TAG_NAMES.get(self.item, self.item)}>"
        if self.count is not None:
            name += f" x{self.count}"
        return name


@dataclass(frozen=True)
class Bound:
    """An inclusive range on one component of a field. None at either end means
    unbounded in that direction."""

    name: str
    low: Optional[float] = None
    high: Optional[float] = None

    def check(self, value) -> Optional[str]:
        """None if value is acceptable, else a message naming the problem."""
        if self.low is not None and value < self.low:
            return f"{self.name} must be at least {self.low}"
        if self.high is not None and value > self.high:
            return f"{self.name} must be at most {self.high}"
        return None


@dataclass(frozen=True)
class FieldSpec:
    key: str
    label: str
    group: str
    editable: bool
    variants: tuple
    finite: bool = False
    bounds: tuple = ()
    resets: tuple = ()
    file: str = "playerdata"
    note: str = ""

    def variant_for(self, data_version: Optional[int]) -> Optional[Variant]:
        """The shape this field takes in a file of the given DataVersion, or
        None if the field did not exist then. Variants are ordered newest
        first, so the first match wins."""
        for variant in self.variants:
            if variant.covers(data_version):
                return variant
        return None


def field_by_key(key: str) -> Optional[FieldSpec]:
    return _BY_KEY.get(key)


def fields_in_group(group: str) -> list:
    return [f for f in FIELDS if f.group == group]


def editable_fields() -> list:
    return [f for f in FIELDS if f.editable]


def resets_for(key: str) -> list:
    """The FieldSpecs that must be written back to their defaults whenever
    `key` is changed. Position is the case that matters: moving a player
    without zeroing motion and fall distance lands them mid-fall at the
    destination, still owed the damage."""
    spec = _BY_KEY.get(key)
    if spec is None:
        return []
    return [_BY_KEY[k] for k in spec.resets if k in _BY_KEY]



# -------------------------------------------------------------------------
# Load-time behaviour, read off the game's own load path.
# -------------------------------------------------------------------------

POS_CLAMP_XZ = 3.0000512e7  # Entity.load clamps X and Z to +/- this
POS_CLAMP_Y = 2.0e7  # Entity.load clamps Y to +/- this
MOTION_DISCARD_ABOVE = 10.0  # Entity.load zeroes any Motion axis above this magnitude
DEFAULT_MAX_HEALTH = 20.0  # when the attributes list carries no max_health entry
DEFAULT_FOOD_LEVEL = 20  # FoodData's initial value


# -------------------------------------------------------------------------
# Members of the shared respawn compound (LevelData.RespawnData,
# plus `forced` on the player side via ServerPlayer.RespawnConfig).
# -------------------------------------------------------------------------

RESPAWN_MEMBERS = (
    Variant(path=('dimension',), tag=TAG_STRING),  # namespaced dimension id
    Variant(path=('pos',), tag=TAG_INT_ARRAY, count=3),  # block position
    Variant(path=('yaw',), tag=TAG_FLOAT),  # Codec.floatRange(-180, 180)
    Variant(path=('pitch',), tag=TAG_FLOAT),  # Codec.floatRange(-90, 90)
    Variant(path=('forced',), tag=TAG_BYTE),  # player respawn only; optional, default 0
)

LEGACY_SPAWN_MEMBERS = (
    Variant(path=('SpawnX',), tag=TAG_INT),  # both sides
    Variant(path=('SpawnY',), tag=TAG_INT),  # both sides
    Variant(path=('SpawnZ',), tag=TAG_INT),  # both sides
    Variant(path=('SpawnAngle',), tag=TAG_FLOAT),  # both sides; the fix renamed it to yaw
    Variant(path=('SpawnDimension',), tag=TAG_STRING),  # player side only, 1.16+
    Variant(path=('SpawnForced',), tag=TAG_BYTE),  # player side only
)


# -------------------------------------------------------------------------
# The fields themselves.
# -------------------------------------------------------------------------

FIELDS = (
    # Pos: Entity.java
    FieldSpec(
        key="pos",
        label="Position",
        group="position",
        editable=True,
        variants=(
            Variant(path=('Pos',), tag=TAG_LIST, item=TAG_DOUBLE, count=3),
        ),
        finite=True,
        bounds=(
            Bound("x", -30000512.0, 30000512.0),
            Bound("y", -20000000.0, 20000000.0),
            Bound("z", -30000512.0, 30000512.0),
        ),
        resets=('motion', 'fall_distance'),
        note=
            "Entity.load clamps each axis to these bounds and throws "
            "IllegalStateException on a non-finite value, which surfaces as a "
            "ReportedException and takes the login with it.",
    ),
    # Motion: Entity.java
    FieldSpec(
        key="motion",
        label="Motion",
        group="position",
        editable=False,
        variants=(
            Variant(path=('Motion',), tag=TAG_LIST, item=TAG_DOUBLE, count=3),
        ),
        finite=True,
        note=
            "Reset to zero whenever position changes. Entity.load already "
            "discards any axis whose magnitude exceeds 10.0, so this is belt- "
            "and-braces rather than the only guard.",
    ),
    # Rotation: Entity.java
    FieldSpec(
        key="rotation",
        label="Rotation",
        group="position",
        editable=False,
        variants=(
            Variant(path=('Rotation',), tag=TAG_LIST, item=TAG_FLOAT, count=2),
        ),
        finite=True,
        note=
            "Yaw then pitch. Non-finite values throw at load exactly as Pos "
            "does, so the repair path has to check them even though the "
            "editor does not offer them.",
    ),
    # fall_distance: Entity.java
    FieldSpec(
        key="fall_distance",
        label="Fall distance",
        group="position",
        editable=False,
        variants=(
            Variant(path=('fall_distance',), tag=TAG_DOUBLE, min_dv=4303),
            Variant(path=('FallDistance',), tag=TAG_FLOAT, max_dv=4302),
        ),
        finite=True,
        note=
            "Renamed and widened to a double by "
            "EntityFallDistanceFloatToDoubleFix. Reset to zero alongside "
            "position, or the player takes the fall damage they were owed "
            "before being moved.",
    ),
    # Dimension: ServerPlayer.java
    FieldSpec(
        key="dimension",
        label="Dimension",
        group="position",
        editable=False,
        variants=(
            Variant(path=('Dimension',), tag=TAG_STRING, min_dv=2537),
            Variant(path=('Dimension',), tag=TAG_INT, max_dv=2536),
        ),
        finite=False,
        note=
            "Display only, but Pos is meaningless without it. Became a "
            "namespaced string at LegacyDimensionIdFix; before that it was "
            "-1/0/1.",
    ),
    # Health: LivingEntity.java
    FieldSpec(
        key="health",
        label="Health",
        group="vitals",
        editable=True,
        variants=(
            Variant(path=('Health',), tag=TAG_FLOAT, min_dv=109),
            Variant(path=('HealF',), tag=TAG_FLOAT, max_dv=108),
            Variant(path=('Health',), tag=TAG_SHORT, max_dv=108),
        ),
        finite=True,
        bounds=(
            Bound("health", 0.0, None),
        ),
        note=
            "setHealth clamps to [0, maxHealth] via Mth.clamp, which is "
            "`value < min ? min : Math.min(value, max)` -- NaN fails both "
            "comparisons and passes straight through, so a NaN here survives "
            "into the running game. A missing tag reads as max health, not "
            "zero. Below DataVersion 109 a file carries both a truncated "
            "short Health and a float HealF; the float is listed first "
            "deliberately, because EntityHealthFix prefers HealF when both "
            "are present and so should any reader.",
    ),
    # attributes: LivingEntity.java
    FieldSpec(
        key="max_health",
        label="Max health",
        group="vitals",
        editable=False,
        variants=(
            Variant(path=('attributes',), tag=TAG_LIST, item=TAG_COMPOUND, min_dv=3945),
            Variant(path=('Attributes',), tag=TAG_LIST, item=TAG_COMPOUND, max_dv=3944),
        ),
        finite=False,
        note=
            "A list of only the attributes that differ from their defaults, "
            "so the normal case is no max_health entry at all, meaning 20. "
            "AttributeModifierIdFix renamed the list and its entry keys "
            "(Name/Base -> id/base); AttributeIdPrefixFix dropped the "
            "'generic.' infix. Read to bound the Health field; editing it is "
            "out of scope for v1.",
    ),
    # foodLevel: FoodData.java
    FieldSpec(
        key="food_level",
        label="Food",
        group="vitals",
        editable=True,
        variants=(
            Variant(path=('foodLevel',), tag=TAG_INT),
        ),
        finite=False,
        bounds=(
            Bound("food", 0, 20),
        ),
        note=
            "FoodData clamps to [0, 20] on every change.",
    ),
    # playerGameType: ServerPlayer.java
    FieldSpec(
        key="gamemode",
        label="Game mode",
        group="mode",
        editable=True,
        variants=(
            Variant(path=('playerGameType',), tag=TAG_INT),
        ),
        finite=False,
        bounds=(
            Bound("mode", 0, 3),
        ),
        note=
            "0 survival, 1 creative, 2 adventure, 3 spectator. Written "
            "through GameType.LEGACY_ID_CODEC, which is a plain int. A server "
            "with force-gamemode set overrides this at login.",
    ),
    # previousPlayerGameType: ServerPlayer.java
    FieldSpec(
        key="previous_gamemode",
        label="Previous game mode",
        group="mode",
        editable=False,
        variants=(
            Variant(path=('previousPlayerGameType',), tag=TAG_INT),
        ),
        finite=False,
        note=
            "Written nullable, so absent rather than -1 on a player who has "
            "never switched.",
    ),
    # XpLevel: Player.java
    FieldSpec(
        key="xp_level",
        label="XP level",
        group="xp",
        editable=True,
        variants=(
            Variant(path=('XpLevel',), tag=TAG_INT),
        ),
        finite=False,
        bounds=(
            Bound("level", 0, None),
        ),
        note="",
    ),
    # XpP: Player.java
    FieldSpec(
        key="xp_progress",
        label="XP progress",
        group="xp",
        editable=True,
        variants=(
            Variant(path=('XpP',), tag=TAG_FLOAT),
        ),
        finite=True,
        bounds=(
            Bound("progress", 0.0, 1.0),
        ),
        note=
            "Fraction of the way to the next level.",
    ),
    # XpTotal: Player.java
    FieldSpec(
        key="xp_total",
        label="XP total",
        group="xp",
        editable=True,
        variants=(
            Variant(path=('XpTotal',), tag=TAG_INT),
        ),
        finite=False,
        bounds=(
            Bound("total", 0, None),
        ),
        note=
            "Lifetime total. Independent of XpLevel/XpP -- editing one "
            "without the others leaves them inconsistent, which the game "
            "tolerates but the scoreboard notices.",
    ),
    # XpSeed: Player.java
    FieldSpec(
        key="xp_seed",
        label="Enchantment seed",
        group="xp",
        editable=False,
        variants=(
            Variant(path=('XpSeed',), tag=TAG_INT),
        ),
        finite=False,
        note=
            "Never write. Determines the enchanting table offers; changing it "
            "rerolls them.",
    ),
    # respawn: ServerPlayer.java
    FieldSpec(
        key="respawn",
        label="Player respawn point",
        group="repair",
        editable=False,
        variants=(
            Variant(path=('respawn',), tag=TAG_COMPOUND, min_dv=4548),
            Variant(path=('SpawnX',), tag=TAG_INT, max_dv=4547),
        ),
        finite=False,
        note=
            "PlayerRespawnDataFix replaced the flat SpawnX/Y/Z + "
            "SpawnDimension/SpawnForced/SpawnAngle tags with a compound of "
            "{dimension: string, pos: int[3], yaw: float, pitch: float, "
            "forced: byte}, sharing LevelData.RespawnData with level.dat. yaw "
            "and pitch are range-checked codecs, so a NaN in either makes the "
            "whole compound fail to parse and ServerPlayer falls back to null "
            "-- the player silently loses their bed spawn. Absent entirely "
            "until a bed or anchor is used, which is the common case.",
    ),
    # spawn: PrimaryLevelData.java
    FieldSpec(
        key="world_spawn",
        label="World spawn",
        group="repair",
        editable=False,
        file="level.dat",
        variants=(
            Variant(path=('Data', 'spawn'), tag=TAG_COMPOUND, min_dv=4548),
            Variant(path=('Data', 'SpawnX'), tag=TAG_INT, max_dv=4547),
        ),
        finite=False,
        note=
            "WorldSpawnDataFix, same schema version and same RespawnData "
            "codec as the player side. It now carries an explicit dimension, "
            "so the fallback no longer has to assume the overworld.",
    ),
)

_BY_KEY = {f.key: f for f in FIELDS}


# -------------------------------------------------------------------------
# Rename history, extracted from the data-fix registry. Every entry is a
# tag that changed name at a known DataVersion -- the reason a reader
# has to match more than one spelling. Filtered to the fields above.
# -------------------------------------------------------------------------

# (data_version, fix_class, old_name, new_name)
RENAMES = (
    (3945, "AttributeModifierIdFix", "Amount", "amount"),
    (3945, "AttributeModifierIdFix", "Attributes", "attributes"),
    (3945, "AttributeModifierIdFix", "Base", "base"),
    (3945, "AttributeModifierIdFix", "Modifiers", "modifiers"),
    (3945, "AttributeModifierIdFix", "Name", "id"),
    (3945, "AttributeModifierIdFix", "Name", "name"),
    (3945, "AttributeModifierIdFix", "Operation", "operation"),
    (3945, "AttributeModifierIdFix", "UUID", "uuid"),
    (4303, "EntityFallDistanceFloatToDoubleFix", "FallDistance", "fall_distance"),
)


# The fixes that reshape (rather than rename) those fields.
# (data_version, fix_class, what it did)
RESHAPES = (
    (109, "EntityHealthFix", "short Health + float HealF -> float Health"),
    (2514, "PlayerUUIDFix", "UUIDLeast/UUIDMost longs -> UUID int array"),
    (2537, "LegacyDimensionIdFix", "Dimension int -> namespaced string"),
    (3945, "AttributeModifierIdFix", "Attributes -> attributes, Name/Base -> id/base"),
    (4055, "AttributeIdPrefixFix", "dropped the 'generic.' infix from attribute ids"),
    (4303, "EntityFallDistanceFloatToDoubleFix", "FallDistance float -> fall_distance double"),
    (4548, "PlayerRespawnDataFix", "flat SpawnX/Y/Z -> respawn compound"),
    (4548, "WorldSpawnDataFix", "flat Data.SpawnX/Y/Z -> Data.spawn compound"),
)
